{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 2,
   "id": "4f750c37-3d39-4d1d-a151-867b7ed65afa",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Collecting pmdarima\n",
      "  Downloading pmdarima-2.0.4-cp312-cp312-win_amd64.whl.metadata (8.0 kB)\n",
      "Requirement already satisfied: joblib>=0.11 in c:\\users\\harmeek\\anaconda3\\lib\\site-packages (from pmdarima) (1.4.2)\n",
      "Collecting Cython!=0.29.18,!=0.29.31,>=0.29 (from pmdarima)\n",
      "  Downloading cython-3.1.1-cp312-cp312-win_amd64.whl.metadata (3.6 kB)\n",
      "Requirement already satisfied: numpy>=1.21.2 in c:\\users\\harmeek\\anaconda3\\lib\\site-packages (from pmdarima) (1.26.4)\n",
      "Requirement already satisfied: pandas>=0.19 in c:\\users\\harmeek\\anaconda3\\lib\\site-packages (from pmdarima) (2.2.2)\n",
      "Requirement already satisfied: scikit-learn>=0.22 in c:\\users\\harmeek\\anaconda3\\lib\\site-packages (from pmdarima) (1.5.1)\n",
      "Requirement already satisfied: scipy>=1.3.2 in c:\\users\\harmeek\\anaconda3\\lib\\site-packages (from pmdarima) (1.13.1)\n",
      "Requirement already satisfied: statsmodels>=0.13.2 in c:\\users\\harmeek\\anaconda3\\lib\\site-packages (from pmdarima) (0.14.2)\n",
      "Requirement already satisfied: urllib3 in c:\\users\\harmeek\\anaconda3\\lib\\site-packages (from pmdarima) (2.2.3)\n",
      "Requirement already satisfied: setuptools!=50.0.0,>=38.6.0 in c:\\users\\harmeek\\anaconda3\\lib\\site-packages (from pmdarima) (75.1.0)\n",
      "Requirement already satisfied: packaging>=17.1 in c:\\users\\harmeek\\anaconda3\\lib\\site-packages (from pmdarima) (24.1)\n",
      "Requirement already satisfied: python-dateutil>=2.8.2 in c:\\users\\harmeek\\anaconda3\\lib\\site-packages (from pandas>=0.19->pmdarima) (2.9.0.post0)\n",
      "Requirement already satisfied: pytz>=2020.1 in c:\\users\\harmeek\\anaconda3\\lib\\site-packages (from pandas>=0.19->pmdarima) (2024.1)\n",
      "Requirement already satisfied: tzdata>=2022.7 in c:\\users\\harmeek\\anaconda3\\lib\\site-packages (from pandas>=0.19->pmdarima) (2023.3)\n",
      "Requirement already satisfied: threadpoolctl>=3.1.0 in c:\\users\\harmeek\\anaconda3\\lib\\site-packages (from scikit-learn>=0.22->pmdarima) (3.5.0)\n",
      "Requirement already satisfied: patsy>=0.5.6 in c:\\users\\harmeek\\anaconda3\\lib\\site-packages (from statsmodels>=0.13.2->pmdarima) (0.5.6)\n",
      "Requirement already satisfied: six in c:\\users\\harmeek\\anaconda3\\lib\\site-packages (from patsy>=0.5.6->statsmodels>=0.13.2->pmdarima) (1.16.0)\n",
      "Downloading pmdarima-2.0.4-cp312-cp312-win_amd64.whl (625 kB)\n",
      "   ---------------------------------------- 0.0/625.1 kB ? eta -:--:--\n",
      "   ---------------------------------------- 625.1/625.1 kB 3.9 MB/s eta 0:00:00\n",
      "Downloading cython-3.1.1-cp312-cp312-win_amd64.whl (2.7 MB)\n",
      "   ---------------------------------------- 0.0/2.7 MB ? eta -:--:--\n",
      "   ------- -------------------------------- 0.5/2.7 MB 5.6 MB/s eta 0:00:01\n",
      "   --------------- ------------------------ 1.0/2.7 MB 2.5 MB/s eta 0:00:01\n",
      "   ------------------- -------------------- 1.3/2.7 MB 2.4 MB/s eta 0:00:01\n",
      "   --------------------------- ------------ 1.8/2.7 MB 2.1 MB/s eta 0:00:01\n",
      "   ----------------------------------- ---- 2.4/2.7 MB 2.2 MB/s eta 0:00:01\n",
      "   ---------------------------------------- 2.7/2.7 MB 2.3 MB/s eta 0:00:00\n",
      "Installing collected packages: Cython, pmdarima\n",
      "Successfully installed Cython-3.1.1 pmdarima-2.0.4\n"
     ]
    }
   ],
   "source": [
    "!pip install pmdarima\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "id": "223fda0e-134d-422f-b1b0-3a79be31e889",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Requirement already satisfied: streamlit in c:\\users\\harmeek\\anaconda3\\lib\\site-packages (1.37.1)\n",
      "Requirement already satisfied: matplotlib in c:\\users\\harmeek\\anaconda3\\lib\\site-packages (3.9.2)\n",
      "Requirement already satisfied: statsmodels in c:\\users\\harmeek\\anaconda3\\lib\\site-packages (0.14.2)\n",
      "Requirement already satisfied: scikit-learn in c:\\users\\harmeek\\anaconda3\\lib\\site-packages (1.5.1)\n",
      "Requirement already satisfied: altair<6,>=4.0 in c:\\users\\harmeek\\anaconda3\\lib\\site-packages (from streamlit) (5.0.1)\n",
      "Requirement already satisfied: blinker<2,>=1.0.0 in c:\\users\\harmeek\\anaconda3\\lib\\site-packages (from streamlit) (1.6.2)\n",
      "Requirement already satisfied: cachetools<6,>=4.0 in c:\\users\\harmeek\\anaconda3\\lib\\site-packages (from streamlit) (5.3.3)\n",
      "Requirement already satisfied: click<9,>=7.0 in c:\\users\\harmeek\\anaconda3\\lib\\site-packages (from streamlit) (8.1.7)\n",
      "Requirement already satisfied: numpy<3,>=1.20 in c:\\users\\harmeek\\anaconda3\\lib\\site-packages (from streamlit) (1.26.4)\n",
      "Requirement already satisfied: packaging<25,>=20 in c:\\users\\harmeek\\anaconda3\\lib\\site-packages (from streamlit) (24.1)\n",
      "Requirement already satisfied: pandas<3,>=1.3.0 in c:\\users\\harmeek\\anaconda3\\lib\\site-packages (from streamlit) (2.2.2)\n",
      "Requirement already satisfied: pillow<11,>=7.1.0 in c:\\users\\harmeek\\anaconda3\\lib\\site-packages (from streamlit) (10.4.0)\n",
      "Requirement already satisfied: protobuf<6,>=3.20 in c:\\users\\harmeek\\anaconda3\\lib\\site-packages (from streamlit) (4.25.3)\n",
      "Requirement already satisfied: pyarrow>=7.0 in c:\\users\\harmeek\\anaconda3\\lib\\site-packages (from streamlit) (16.1.0)\n",
      "Requirement already satisfied: requests<3,>=2.27 in c:\\users\\harmeek\\anaconda3\\lib\\site-packages (from streamlit) (2.32.3)\n",
      "Requirement already satisfied: rich<14,>=10.14.0 in c:\\users\\harmeek\\anaconda3\\lib\\site-packages (from streamlit) (13.7.1)\n",
      "Requirement already satisfied: tenacity<9,>=8.1.0 in c:\\users\\harmeek\\anaconda3\\lib\\site-packages (from streamlit) (8.2.3)\n",
      "Requirement already satisfied: toml<2,>=0.10.1 in c:\\users\\harmeek\\anaconda3\\lib\\site-packages (from streamlit) (0.10.2)\n",
      "Requirement already satisfied: typing-extensions<5,>=4.3.0 in c:\\users\\harmeek\\anaconda3\\lib\\site-packages (from streamlit) (4.11.0)\n",
      "Requirement already satisfied: gitpython!=3.1.19,<4,>=3.0.7 in c:\\users\\harmeek\\anaconda3\\lib\\site-packages (from streamlit) (3.1.43)\n",
      "Requirement already satisfied: pydeck<1,>=0.8.0b4 in c:\\users\\harmeek\\anaconda3\\lib\\site-packages (from streamlit) (0.8.0)\n",
      "Requirement already satisfied: tornado<7,>=6.0.3 in c:\\users\\harmeek\\anaconda3\\lib\\site-packages (from streamlit) (6.4.1)\n",
      "Requirement already satisfied: watchdog<5,>=2.1.5 in c:\\users\\harmeek\\anaconda3\\lib\\site-packages (from streamlit) (4.0.1)\n",
      "Requirement already satisfied: contourpy>=1.0.1 in c:\\users\\harmeek\\anaconda3\\lib\\site-packages (from matplotlib) (1.2.0)\n",
      "Requirement already satisfied: cycler>=0.10 in c:\\users\\harmeek\\anaconda3\\lib\\site-packages (from matplotlib) (0.11.0)\n",
      "Requirement already satisfied: fonttools>=4.22.0 in c:\\users\\harmeek\\anaconda3\\lib\\site-packages (from matplotlib) (4.51.0)\n",
      "Requirement already satisfied: kiwisolver>=1.3.1 in c:\\users\\harmeek\\anaconda3\\lib\\site-packages (from matplotlib) (1.4.4)\n",
      "Requirement already satisfied: pyparsing>=2.3.1 in c:\\users\\harmeek\\anaconda3\\lib\\site-packages (from matplotlib) (3.1.2)\n",
      "Requirement already satisfied: python-dateutil>=2.7 in c:\\users\\harmeek\\anaconda3\\lib\\site-packages (from matplotlib) (2.9.0.post0)\n",
      "Requirement already satisfied: scipy!=1.9.2,>=1.8 in c:\\users\\harmeek\\anaconda3\\lib\\site-packages (from statsmodels) (1.13.1)\n",
      "Requirement already satisfied: patsy>=0.5.6 in c:\\users\\harmeek\\anaconda3\\lib\\site-packages (from statsmodels) (0.5.6)\n",
      "Requirement already satisfied: joblib>=1.2.0 in c:\\users\\harmeek\\anaconda3\\lib\\site-packages (from scikit-learn) (1.4.2)\n",
      "Requirement already satisfied: threadpoolctl>=3.1.0 in c:\\users\\harmeek\\anaconda3\\lib\\site-packages (from scikit-learn) (3.5.0)\n",
      "Requirement already satisfied: jinja2 in c:\\users\\harmeek\\anaconda3\\lib\\site-packages (from altair<6,>=4.0->streamlit) (3.1.4)\n",
      "Requirement already satisfied: jsonschema>=3.0 in c:\\users\\harmeek\\anaconda3\\lib\\site-packages (from altair<6,>=4.0->streamlit) (4.23.0)\n",
      "Requirement already satisfied: toolz in c:\\users\\harmeek\\anaconda3\\lib\\site-packages (from altair<6,>=4.0->streamlit) (0.12.0)\n",
      "Requirement already satisfied: colorama in c:\\users\\harmeek\\anaconda3\\lib\\site-packages (from click<9,>=7.0->streamlit) (0.4.6)\n",
      "Requirement already satisfied: gitdb<5,>=4.0.1 in c:\\users\\harmeek\\anaconda3\\lib\\site-packages (from gitpython!=3.1.19,<4,>=3.0.7->streamlit) (4.0.7)\n",
      "Requirement already satisfied: pytz>=2020.1 in c:\\users\\harmeek\\anaconda3\\lib\\site-packages (from pandas<3,>=1.3.0->streamlit) (2024.1)\n",
      "Requirement already satisfied: tzdata>=2022.7 in c:\\users\\harmeek\\anaconda3\\lib\\site-packages (from pandas<3,>=1.3.0->streamlit) (2023.3)\n",
      "Requirement already satisfied: six in c:\\users\\harmeek\\anaconda3\\lib\\site-packages (from patsy>=0.5.6->statsmodels) (1.16.0)\n",
      "Requirement already satisfied: charset-normalizer<4,>=2 in c:\\users\\harmeek\\anaconda3\\lib\\site-packages (from requests<3,>=2.27->streamlit) (3.3.2)\n",
      "Requirement already satisfied: idna<4,>=2.5 in c:\\users\\harmeek\\anaconda3\\lib\\site-packages (from requests<3,>=2.27->streamlit) (3.7)\n",
      "Requirement already satisfied: urllib3<3,>=1.21.1 in c:\\users\\harmeek\\anaconda3\\lib\\site-packages (from requests<3,>=2.27->streamlit) (2.2.3)\n",
      "Requirement already satisfied: certifi>=2017.4.17 in c:\\users\\harmeek\\anaconda3\\lib\\site-packages (from requests<3,>=2.27->streamlit) (2024.8.30)\n",
      "Requirement already satisfied: markdown-it-py>=2.2.0 in c:\\users\\harmeek\\anaconda3\\lib\\site-packages (from rich<14,>=10.14.0->streamlit) (2.2.0)\n",
      "Requirement already satisfied: pygments<3.0.0,>=2.13.0 in c:\\users\\harmeek\\anaconda3\\lib\\site-packages (from rich<14,>=10.14.0->streamlit) (2.15.1)\n",
      "Requirement already satisfied: smmap<5,>=3.0.1 in c:\\users\\harmeek\\anaconda3\\lib\\site-packages (from gitdb<5,>=4.0.1->gitpython!=3.1.19,<4,>=3.0.7->streamlit) (4.0.0)\n",
      "Requirement already satisfied: MarkupSafe>=2.0 in c:\\users\\harmeek\\anaconda3\\lib\\site-packages (from jinja2->altair<6,>=4.0->streamlit) (2.1.3)\n",
      "Requirement already satisfied: attrs>=22.2.0 in c:\\users\\harmeek\\anaconda3\\lib\\site-packages (from jsonschema>=3.0->altair<6,>=4.0->streamlit) (23.1.0)\n",
      "Requirement already satisfied: jsonschema-specifications>=2023.03.6 in c:\\users\\harmeek\\anaconda3\\lib\\site-packages (from jsonschema>=3.0->altair<6,>=4.0->streamlit) (2023.7.1)\n",
      "Requirement already satisfied: referencing>=0.28.4 in c:\\users\\harmeek\\anaconda3\\lib\\site-packages (from jsonschema>=3.0->altair<6,>=4.0->streamlit) (0.30.2)\n",
      "Requirement already satisfied: rpds-py>=0.7.1 in c:\\users\\harmeek\\anaconda3\\lib\\site-packages (from jsonschema>=3.0->altair<6,>=4.0->streamlit) (0.10.6)\n",
      "Requirement already satisfied: mdurl~=0.1 in c:\\users\\harmeek\\anaconda3\\lib\\site-packages (from markdown-it-py>=2.2.0->rich<14,>=10.14.0->streamlit) (0.1.0)\n"
     ]
    }
   ],
   "source": [
    "!pip install streamlit matplotlib statsmodels scikit-learn\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 8,
   "id": "852c555a-c190-46bb-87ba-b71db568a43e",
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2025-06-02 14:34:37.704 No runtime found, using MemoryCacheStorageManager\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Performing stepwise search to minimize aic\n",
      " ARIMA(2,1,2)(1,0,1)[7] intercept   : AIC=17710.143, Time=7.92 sec\n",
      " ARIMA(0,1,0)(0,0,0)[7] intercept   : AIC=17957.981, Time=0.12 sec\n",
      " ARIMA(1,1,0)(1,0,0)[7] intercept   : AIC=17721.809, Time=0.85 sec\n",
      " ARIMA(0,1,1)(0,0,1)[7] intercept   : AIC=17754.561, Time=1.09 sec\n",
      " ARIMA(0,1,0)(0,0,0)[7]             : AIC=17956.465, Time=0.08 sec\n",
      " ARIMA(2,1,2)(0,0,1)[7] intercept   : AIC=17711.571, Time=4.06 sec\n",
      " ARIMA(2,1,2)(1,0,0)[7] intercept   : AIC=17712.349, Time=4.18 sec\n",
      " ARIMA(2,1,2)(2,0,1)[7] intercept   : AIC=17697.137, Time=12.94 sec\n",
      " ARIMA(2,1,2)(2,0,0)[7] intercept   : AIC=17696.889, Time=10.50 sec\n",
      " ARIMA(1,1,2)(2,0,0)[7] intercept   : AIC=17698.248, Time=6.29 sec\n",
      " ARIMA(2,1,1)(2,0,0)[7] intercept   : AIC=17699.005, Time=7.25 sec\n",
      " ARIMA(3,1,2)(2,0,0)[7] intercept   : AIC=17689.529, Time=21.22 sec\n",
      " ARIMA(3,1,2)(1,0,0)[7] intercept   : AIC=17706.830, Time=10.71 sec\n",
      " ARIMA(3,1,2)(2,0,1)[7] intercept   : AIC=17689.394, Time=25.85 sec\n",
      " ARIMA(3,1,2)(1,0,1)[7] intercept   : AIC=17705.344, Time=10.41 sec\n",
      " ARIMA(3,1,2)(2,0,2)[7] intercept   : AIC=inf, Time=15.51 sec\n",
      " ARIMA(3,1,2)(1,0,2)[7] intercept   : AIC=17693.683, Time=24.49 sec\n",
      " ARIMA(3,1,1)(2,0,1)[7] intercept   : AIC=17701.516, Time=9.32 sec\n",
      " ARIMA(4,1,2)(2,0,1)[7] intercept   : AIC=17666.384, Time=25.31 sec\n",
      " ARIMA(4,1,2)(1,0,1)[7] intercept   : AIC=17701.525, Time=14.86 sec\n",
      " ARIMA(4,1,2)(2,0,0)[7] intercept   : AIC=17670.171, Time=20.90 sec\n",
      " ARIMA(4,1,2)(2,0,2)[7] intercept   : AIC=inf, Time=19.79 sec\n",
      " ARIMA(4,1,2)(1,0,0)[7] intercept   : AIC=17708.218, Time=8.78 sec\n",
      " ARIMA(4,1,2)(1,0,2)[7] intercept   : AIC=17654.640, Time=19.82 sec\n",
      " ARIMA(4,1,2)(0,0,2)[7] intercept   : AIC=17677.372, Time=18.13 sec\n",
      " ARIMA(4,1,2)(0,0,1)[7] intercept   : AIC=17707.861, Time=11.15 sec\n",
      " ARIMA(4,1,1)(1,0,2)[7] intercept   : AIC=17689.195, Time=13.41 sec\n",
      " ARIMA(5,1,2)(1,0,2)[7] intercept   : AIC=17548.890, Time=20.23 sec\n",
      " ARIMA(5,1,2)(0,0,2)[7] intercept   : AIC=inf, Time=16.24 sec\n",
      " ARIMA(5,1,2)(1,0,1)[7] intercept   : AIC=inf, Time=14.20 sec\n",
      " ARIMA(5,1,2)(2,0,2)[7] intercept   : AIC=inf, Time=28.27 sec\n",
      " ARIMA(5,1,2)(0,0,1)[7] intercept   : AIC=17699.451, Time=14.73 sec\n",
      " ARIMA(5,1,2)(2,0,1)[7] intercept   : AIC=17543.513, Time=24.71 sec\n",
      " ARIMA(5,1,2)(2,0,0)[7] intercept   : AIC=17536.236, Time=24.29 sec\n",
      " ARIMA(5,1,2)(1,0,0)[7] intercept   : AIC=17705.898, Time=10.34 sec\n",
      " ARIMA(5,1,1)(2,0,0)[7] intercept   : AIC=17688.557, Time=12.03 sec\n",
      " ARIMA(5,1,3)(2,0,0)[7] intercept   : AIC=17657.785, Time=21.38 sec\n",
      " ARIMA(4,1,1)(2,0,0)[7] intercept   : AIC=17686.616, Time=11.69 sec\n",
      " ARIMA(4,1,3)(2,0,0)[7] intercept   : AIC=17601.430, Time=22.42 sec\n",
      " ARIMA(5,1,2)(2,0,0)[7]             : AIC=17540.255, Time=14.26 sec\n",
      "\n",
      "Best model:  ARIMA(5,1,2)(2,0,0)[7] intercept\n",
      "Total fit time: 559.872 seconds\n"
     ]
    }
   ],
   "source": [
    "# Required Libraries\n",
    "import pandas as pd\n",
    "import numpy as np\n",
    "import matplotlib.pyplot as plt\n",
    "from pmdarima import auto_arima\n",
    "from statsmodels.tsa.statespace.sarimax import SARIMAX\n",
    "import streamlit as st\n",
    "\n",
    "# Load Data\n",
    "@st.cache_data\n",
    "def load_data():\n",
    "    df = pd.read_csv(\"AAPL (4).csv\")\n",
    "    df['Date'] = pd.to_datetime(df['Date'], errors='coerce')\n",
    "    df.dropna(subset=['Date'], inplace=True)\n",
    "    df.sort_values('Date', inplace=True)\n",
    "    df.set_index('Date', inplace=True)\n",
    "    data = df['Close'].asfreq('D')\n",
    "    return data.interpolate(method='time')\n",
    "\n",
    "# Forecast Function\n",
    "def forecast_prices(data, steps=30):\n",
    "    train = data[:-steps]\n",
    "    test = data[-steps:]\n",
    "\n",
    "    # Auto ARIMA for best model\n",
    "    model = auto_arima(train, seasonal=True, m=7, trace=True,\n",
    "                       error_action='ignore', suppress_warnings=True)\n",
    "    \n",
    "\n",
    "    \n",
    "    # Fit best SARIMA model\n",
    "    sarimax = SARIMAX(train, order=(1, 1, 1), seasonal_order=(1, 1, 1, 7),\n",
    "                enforce_stationarity=False, enforce_invertibility=False)\n",
    "\n",
    "    #sarimax = SARIMAX(train, order=model.order, seasonal_order=model.seasonal_order)\n",
    "    result = sarimax.fit()\n",
    "    forecast = result.forecast(steps=steps)\n",
    "    return train, test, forecast, result\n",
    "\n",
    "# Streamlit UI\n",
    "st.title(\"📈 Apple Stock Price Forecast (ARIMA/SARIMA)\")\n",
    "data = load_data()\n",
    "\n",
    "# User input\n",
    "st.sidebar.header(\"Forecast Settings\")\n",
    "steps = st.sidebar.slider(\"Forecast Days\", 7, 60, 30)\n",
    "\n",
    "# Forecast\n",
    "train, test, forecast, result = forecast_prices(data, steps)\n",
    "\n",
    "# Plot\n",
    "st.subheader(\"Forecast vs Actual\")\n",
    "fig, ax = plt.subplots(figsize=(10, 5))\n",
    "train.plot(ax=ax, label=\"Train\")\n",
    "test.plot(ax=ax, label=\"Actual\")\n",
    "forecast.plot(ax=ax, label=\"Forecast\", style='--')\n",
    "plt.legend()\n",
    "st.pyplot(fig)\n",
    "\n",
    "# Metrics\n",
    "from sklearn.metrics import mean_squared_error\n",
    "rmse = np.sqrt(mean_squared_error(test, forecast))\n",
    "st.metric(\"Root Mean Squared Error (RMSE)\", f\"{rmse:.2f}\")\n",
    "import pickle\n",
    "\n",
    "# Save model after training\n",
    "with open(\"model.pkl\", \"wb\") as f:\n",
    "    pickle.dump(result, f)\n",
    "\n",
    "# Load saved SARIMA model\n",
    "with open(\"model.pkl\", \"rb\") as f:\n",
    "    result = pickle.load(f)\n",
    "forecast = result.forecast(steps=steps)\n",
    "\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "26aa964c-2206-4f8b-8d90-2e1498f667bb",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.12.7"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
